#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "gris_commons.h"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;


layout(binding = 0, rgba32f) uniform image2D image;
layout(binding = 1) uniform _SceneUBO { SceneUBO ubo; };
layout(binding = 2) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCReSTIRPT pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer DebugVisBuffer { uint d[]; };

DebugVisBuffer debug_vis = DebugVisBuffer(scene_desc.debug_vis_addr);
void main() {
    uint idx = gl_GlobalInvocationID.x;
    ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.size_y, gl_GlobalInvocationID.x % pc.size_y);
    
    if (pc.pixel_debug == 1) {
        uint rejected_count = debug_vis.d[idx];
        float ratio = float(rejected_count) / max(float(pc.num_spatial_samples), 1.0);
        vec3 color = mix(vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0), ratio);
        imageStore(image, coords, vec4(color, 1.0));
    } else if(pc.gris_separator < 1.0) {
        int x = int(gl_GlobalInvocationID.x) / int(pc.size_y);
        float uv_x =  float(x) / float(pc.size_x);
        float line = clamp(1.0 - abs(uv_x - pc.gris_separator), 0, 1);
        if(line > 0.999) {
            ivec2 coords = ivec2(x, gl_GlobalInvocationID.x % pc.size_y);
            imageStore(image, ivec2(coords), vec4(vec3(1,0,0), 1.f));
        }
    }

}