#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

// #define SCENE_TEX_IDX 9
#define SCENE_TEX_IDX 12
#include "gris_commons.glsl"
PrefixContributions prefix_contributions = PrefixContributions(scene_desc.prefix_contributions_addr);
layout(binding = 4, scalar) buffer CurrResHeaders { Reservoir curr_headers[]; };
layout(binding = 5, scalar) readonly buffer PrevResHeaders { Reservoir prev_headers[]; };
layout(binding = 6, scalar) readonly buffer CurrGBuffer { GBuffer curr_gbuffers[]; };
layout(binding = 7, scalar) readonly buffer PrevGBuffer { GBuffer prev_gbuffers[]; };
layout(binding = 8, rgba16) uniform image2D canonical_contributions_tex;
layout(binding = 9, scalar) buffer CurrImportanceFlags { uint curr_flags[]; };
layout(binding = 10, scalar) readonly buffer PrevImportanceFlags { uint prev_flags[]; };
layout(binding = 11, scalar) buffer CompactData { GrisData compact_data[]; };
uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.seed3);

ivec2 get_permuted_coords(inout uvec4 seed, ivec2 coords) {
	uvec2 rands = uvec2(floatBitsToUint(rand(seed)), floatBitsToUint(rand(seed)));
	ivec2 offset = ivec2(rands.x & 3, (rands.y >> 2) & 3);
	ivec2 new_coords = coords + offset;
	new_coords ^= ivec2(3);
	new_coords -= offset;
	return new_coords;
}

void main() {
	FullReservoir reservoir;
	init_reservoir(reservoir);
	GBuffer gbuffer = curr_gbuffers[pixel_idx];
	if (!gbuffer_data_valid(gbuffer)) {
		return;
	}

	uint canonical_slot = curr_flags[pixel_idx];
	if (canonical_slot == IMPORTANCE_INVALID) return;

	FullReservoir canonical_reservoir;
	canonical_reservoir.header = curr_headers[pixel_idx];
	canonical_reservoir.data = compact_data[canonical_slot];

	HitData canonical_gbuffer =
		get_hitdata(gbuffer.barycentrics, gbuffer.primitive_instance_id.y, gbuffer.primitive_instance_id.x);
	vec4 prev_pos = ubo.prev_view * vec4(canonical_gbuffer.pos, 1);
	prev_pos /= prev_pos.z;
	prev_pos = -ubo.prev_projection * prev_pos;
	vec2 jitter =  pc.enable_temporal_jitter == 1 ? rand2(seed) - 0.5 : vec2(0);
	ivec2 prev_coords = ivec2(0.5 * (1 + prev_pos.xy) * gl_LaunchSizeEXT.xy + jitter);

	if (pc.permutation_sampling == 1) {
		prev_coords = get_permuted_coords(seed, prev_coords);
	}

	float m_c = 0;
	float canonical_in_canonical_pdf = canonical_reservoir.data.reservoir_contribution;
	vec3 curr_reservoir_contribution = vec3(0);
	bool prev_accepted = false;
	float new_jacobian;

	if (!(any(lessThan(prev_coords, ivec2(0))) || any(greaterThanEqual(prev_coords, gl_LaunchSizeEXT.xy)))) {
		const uint prev_idx = prev_coords.x * pc.size_y + prev_coords.y;
		GBuffer prev_gbuffer = prev_gbuffers[prev_idx];
		if (gbuffer_data_valid(prev_gbuffer)) {
			Reservoir prev_header = prev_headers[prev_idx];
			
			if (prev_header.M > 0) {
				uint prev_slot = prev_flags[prev_idx];
				if (prev_slot != IMPORTANCE_INVALID) {
					ReconnectionData data;
					data.reservoir_contribution = vec3(0);
					data.jacobian = 0;
					data.target_pdf_in_neighbor = 0;

					FullReservoir prev_reservoir;
					prev_reservoir.header = prev_header;
					prev_reservoir.data = compact_data[prev_slot];

					HitData prev_hitdata = get_hitdata(prev_gbuffer.barycentrics, prev_gbuffer.primitive_instance_id.y,
													prev_gbuffer.primitive_instance_id.x);

					vec3 primary_direction = get_primary_direction(uvec2(gl_LaunchIDEXT.xy));
					vec3 prev_primary_direction = get_prev_primary_direction(uvec2(prev_coords));
					retrace_paths(canonical_gbuffer, prev_reservoir.data, primary_direction,
								prev_reservoir.data.rc_partial_jacobian, data.jacobian, data.reservoir_contribution,
								new_jacobian);

					retrace_paths_and_evaluate(prev_hitdata, canonical_reservoir.data, prev_primary_direction,
											data.target_pdf_in_neighbor);

					prev_accepted = process_reservoir(seed, reservoir, m_c, canonical_reservoir, prev_reservoir, data,
													prev_coords, canonical_in_canonical_pdf, 1, curr_reservoir_contribution);
				}
			}											  
		}
	}

	// Stream in the canonical reservoir
	m_c = m_c == 0 ? 1.0 : m_c;
	bool canonical = combine_reservoir(seed, reservoir, canonical_reservoir, canonical_in_canonical_pdf, m_c, 1.0);
	if (canonical) {
		curr_reservoir_contribution = imageLoad(canonical_contributions_tex, ivec2(gl_LaunchIDEXT.xy)).xyz;
	} else {
		imageStore(canonical_contributions_tex, ivec2(gl_LaunchIDEXT.xy), vec4(curr_reservoir_contribution, 0));
	}
	float target_pdf = calc_target_pdf(curr_reservoir_contribution);
	calc_reservoir_W_with_mis(reservoir);

	if (prev_accepted && !canonical) {
		reservoir.data.rc_partial_jacobian = new_jacobian;
		reservoir.data.reservoir_contribution = calc_target_pdf(curr_reservoir_contribution);
	}

	curr_headers[pixel_idx] = reservoir.header;
	compact_data[canonical_slot] = reservoir.data;
}